### ISSUE TITLE
Windows Janky Server appears to be offline

### ISSUE THREAD

**Issue by Haacked** [github/janky#185]
We have a couple of builds queued up but they're not running.

As an aside, it'd be nice if when builds are queued up, they would post an "in-progress" commit status. Right now, those PRs appear green even though they haven't built yet.

/cc @keithduncan

**Comment by mattr-** [comment]
Janky has an queued/in-progress indicator now and the rest of it looks like it might be an internal GitHub    issue from before the repo was open-sourced, so I'll just give it the ol' heave-ho. :smiley:
