### ISSUE TITLE
Install Locally

### ISSUE THREAD

**Issue by jcampbell05** [github/janky#214]
Do you have an instructions for installing locally not on heruku ? We ant to deploy on our own mac mini server is this easy ?

**Comment by MitchK** [comment]
I would also like to setup Janky not just locally, but with Docker. Some more documentation would be awesome!

**Comment by mkantor** [comment]
I did this recently using <http://ddollar.github.io/foreman/> and it was pretty straightforward. You'll have to create the DB and make sure you have configs set as environment variables, but foreman should do the rest.

**Comment by mieciu** [comment]
Here you can find out how to run app locally

https://github.com/github/janky#hacking

**Comment by mattr-** [comment]
You should be able to clone [this gist](https://gist.github.com/sr/1497335) to use as a starting point until I have a chance to put some better documentation in place.
