### ISSUE TITLE
Janky with role / matrix based jenkins?

### ISSUE THREAD

**Issue by dvcrn** [github/janky#220]
Hi,

am I missing something here? I'm trying to set up janky with our jenkins but can't manage to get a connection working. Is only basic auth supported for logging in? If so, are other auth providers planned?

Our jenkins uses role based authentication. 

Config:

```
JANKY_BASE_URL:            https://somejankydomain.herokuapp.com/
JANKY_BUILDER_DEFAULT:     http://user:pass@jenkins.somedomain.com/
JANKY_CHAT:                hubot
JANKY_CHAT_HUBOT_URL:      https://someapp.herokuapp.com/
JANKY_CONFIG_DIR:          /app/config
JANKY_GITHUB_HOOK_SECRET:  some-token
JANKY_GITHUB_PASSWORD:     some-pass
JANKY_GITHUB_STATUS_TOKEN: some-token
JANKY_GITHUB_USER:         github-bot
JANKY_HUBOT_PASSWORD:      somepass
JANKY_HUBOT_USER:          someuser
LANG:                      en_US.UTF-8
RACK_ENV:                  production
```

Other side question out of curiosity - is github still behind janky and using it?

**Comment by mattr-** [comment]
GitHub is no longer behind janky. They've switched to using something internal.

Basic auth is the only thing supported for logging in. No other auth providers are planned. Janky's whole raison d'être is to hide Jenkins behind it's own much simpler but much less featureful frontend and to limit access to that frontend based on GitHub credentials.

**Comment by dvcrn** [comment]
Thanks for the clarification!

**Comment by mattr-** [comment]
I discovered recently that GitHub authentication can be combined with Basic Auth for API usage, so it's possible that we may end up supporting GitHub authentication in the near future using that mechanism. 

Basic auth is still the way to go for now though.
