### ISSUE TITLE
[Question]Do itsupport private deployment?

### ISSUE THREAD

**Issue by yileye** [github/janky#224]

**Comment by yileye** [comment]
Do it support private env deploy

**Comment by mattr-** [comment]
I'm very sorry. I thought I'd replied to this issue already.

Heroku isn't a requirement for deploying Janky. You can deploy Janky to any system that will host a Rails project, although we don't have good documentation for that yet. I've done this at several of the companies that I've been at and put Janky in place. Let me know if you're having a specific issue and I'll do my best to help you out.

Thanks!

**Comment by yileye** [comment]
How to deploy janky to local environment？

We already have jenkins and gitlab

**Comment by mattr-** [comment]
Janky works on top of Jenkins, so I would imagine you could follow [this gist](https://gist.github.com/sr/1497335) and make the necessary modifications for your local environment rather than Heroku.
